{"uuid": "939b8d0e-c6ec-4824-910c-a21256408819", "children": ["ef344a43-faa2-4af2-a4db-03ab13efbaf9"], "befores": [{"name": "login_valid", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n\tGetHandleVerifier [0x0x90c333+65459]\n\tGetHandleVerifier [0x0x90c374+65524]\n\t(No symbol) [0x0x72d973]\n\t(No symbol) [0x0x7776e7]\n\t(No symbol) [0x0x777a8b]\n\t(No symbol) [0x0x7bdea2]\n\t(No symbol) [0x0x799e44]\n\t(No symbol) [0x0x7bb606]\n\t(No symbol) [0x0x799bf6]\n\t(No symbol) [0x0x76b38e]\n\t(No symbol) [0x0x76c274]\n\tGetHandleVerifier [0x0xb8eda3+2697763]\n\tGetHandleVerifier [0x0xb89ec7+2677575]\n\tGetHandleVerifier [0x0x934194+228884]\n\tGetHandleVerifier [0x0x9249f8+165496]\n\tGetHandleVerifier [0x0x92b18d+192013]\n\tGetHandleVerifier [0x0x9147d8+99416]\n\tGetHandleVerifier [0x0x914972+99826]\n\tGetHandleVerifier [0x0x8febea+10346]\n\tBaseThreadInitThunk [0x0x76307ba9+25]\n\tRtlInitializeExceptionChain [0x0x7788c2eb+107]\n\tRtlClearBits [0x0x7788c26f+191]\n\n", "trace": "  File \"C:\\Users\\shahn\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\shahn\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\shahn\\orangeHRM_project\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\shahn\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\shahn\\orangeHRM_project\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\shahn\\orangeHRM_project\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\shahn\\orangeHRM_project\\tests\\Recruitment\\test_vacancy.py\", line 12, in login_valid\n    login_page.login(\"Admin\", \"admin123\")  # use correct creds\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahn\\orangeHRM_project\\pages\\login_page.py\", line 26, in login\n    self.enter_text(self.USERNAME_INPUT, username)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahn\\orangeHRM_project\\pages\\base_page.py\", line 30, in enter_text\n    element = self.find_element(locator)\n  File \"C:\\Users\\shahn\\orangeHRM_project\\pages\\base_page.py\", line 16, in find_element\n    return self.wait.until(EC.presence_of_element_located(locator))\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahn\\orangeHRM_project\\.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1759831150613, "stop": 1759831171185}], "start": 1759831150613, "stop": 1759831171273}